import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { Button } from 'react-bootstrap'
import { removeSession } from '@/lib/auth'
import { useRouter } from 'next/router'
import { AppNavBar } from '@/components/UserNavBar'

export default function Home() {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppNavBar />
      <main className={styles.main}>
        <Button onClick={() => {}}>Does nothing</Button>
      </main>
    </>
  )
}
