import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { Button } from 'react-bootstrap'
import { useRouter } from 'next/router'
import { AppNavBar } from '@/components/UserNavBar'
import { fetchGet } from '@/lib/fetch'
import { useEffect, useState } from 'react'
import { Project } from '@/components/Project'

export default function Home() {
  const router = useRouter();

  const [data, setData] = useState<any>([]);

  useEffect(() => {
    fetchGet('/api/outstanding').then(data => {
      setData(data);
    })
  }, [])

  const projects = data.map((p: any) => <Project data={p} key={p.id} />)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppNavBar />
      <main className={styles.main}>
        {projects}
        <Button onClick={() => {}}>Does nothing</Button>
      </main>
    </>
  )
}
